### ISSUE TITLE
Status / package name

### ISSUE THREAD

**Issue by flyx** [nim-appkit/yaml#1]
nimble will soon enforce that main module name == package name. Since I also have a module `yaml` in my [NimYAML](http://flyx.github.io/NimYAML) package, I would need to rename that module because you hold the package name `yaml` with this project.

Therefore, I want to query the status of this project. If you do not plan on continuing to develop it, I want to respectfully request to rename your package so that I can use the package name `yaml`.

**Comment by theduke** [comment]
I won't work on this package anymore.
You can remove it from the nimble index, which should be done anyway since I wont maintain it.

Just open a pr removing the package and link this issue to show I'm ok with it.
